CREATE TABLE investment_sequences (book_id TEXT PRIMARY KEY, last_sequence INTEGER NOT NULL CHECK (last_sequence >= 0 AND last_sequence <= 9223372036854775807), FOREIGN KEY (book_id) REFERENCES financial_books (id)) STRICT;
CREATE TABLE investment_operations (
  id TEXT PRIMARY KEY, book_id TEXT NOT NULL, position_id TEXT NOT NULL, type TEXT NOT NULL CHECK (type IN ('OPENING_ALLOCATION','APPLICATION','PURCHASE','SALE','REDEMPTION','INCOME','AMORTIZATION','FEE','TAX')), role TEXT NOT NULL CHECK (role IN ('BUSINESS','REVERSAL')),
  occurred_on TEXT NOT NULL, settled_on TEXT, recorded_at TEXT NOT NULL, sequence INTEGER NOT NULL CHECK (sequence > 0), description TEXT NOT NULL, currency TEXT NOT NULL CHECK (currency GLOB '[A-Z][A-Z][A-Z]'), quantity_delta TEXT, book_cost_delta_minor INTEGER NOT NULL, gross_amount_minor INTEGER NOT NULL, fees_minor INTEGER NOT NULL, taxes_minor INTEGER NOT NULL, net_cash_flow_minor INTEGER NOT NULL,
  cash_mode TEXT NOT NULL CHECK (cash_mode IN ('NONE','INTERNAL_CASH','EXTERNAL_ACCOUNT')), settlement_account_id TEXT, gain_category_id TEXT, loss_category_id TEXT, income_category_id TEXT, fee_category_id TEXT, tax_category_id TEXT,
  before_kind TEXT NOT NULL CHECK (before_kind IN ('UNOPENED','EXISTING')), before_quantity TEXT, before_book_cost_minor INTEGER, before_status TEXT CHECK (before_status IN ('OPEN','CLOSED')), before_opened_on TEXT, before_closed_on TEXT, before_allocation_effective_on TEXT,
  journal_entry_id TEXT, reversal_of_id TEXT, reversed_by_id TEXT, replacement_of_id TEXT, replaced_by_id TEXT, version INTEGER NOT NULL CHECK (version >= 0),
  UNIQUE (id, book_id), UNIQUE (id, book_id, position_id), UNIQUE (book_id, sequence), FOREIGN KEY (position_id, book_id) REFERENCES investment_positions (id, book_id), FOREIGN KEY (journal_entry_id, book_id) REFERENCES journal_entries (id, book_id), FOREIGN KEY (settlement_account_id, book_id) REFERENCES ledger_accounts (id, book_id), FOREIGN KEY (reversal_of_id, book_id, position_id) REFERENCES investment_operations (id, book_id, position_id), FOREIGN KEY (reversed_by_id, book_id, position_id) REFERENCES investment_operations (id, book_id, position_id), FOREIGN KEY (replacement_of_id, book_id, position_id) REFERENCES investment_operations (id, book_id, position_id), FOREIGN KEY (replaced_by_id, book_id, position_id) REFERENCES investment_operations (id, book_id, position_id),
  CHECK ((cash_mode = 'EXTERNAL_ACCOUNT') = (settlement_account_id IS NOT NULL)), CHECK ((role = 'REVERSAL' AND reversal_of_id IS NOT NULL AND reversed_by_id IS NULL AND replaced_by_id IS NULL) OR role = 'BUSINESS'), CHECK (id <> reversal_of_id AND id <> reversed_by_id AND id <> replacement_of_id AND id <> replaced_by_id)
) STRICT;
CREATE UNIQUE INDEX ux_investment_operations_journal ON investment_operations (book_id, journal_entry_id) WHERE journal_entry_id IS NOT NULL;
CREATE INDEX ix_investment_operations_history ON investment_operations (book_id, position_id, occurred_on DESC, sequence DESC);
CREATE INDEX ix_investment_operations_effective ON investment_operations (book_id, position_id, occurred_on DESC, sequence DESC) WHERE role = 'BUSINESS' AND reversed_by_id IS NULL AND replaced_by_id IS NULL;
CREATE TRIGGER trg_investment_operations_effect_immutable BEFORE UPDATE OF occurred_on, settled_on, recorded_at, sequence, quantity_delta, book_cost_delta_minor, gross_amount_minor, fees_minor, taxes_minor, net_cash_flow_minor ON investment_operations BEGIN SELECT RAISE(ABORT, 'investment operation effects are immutable'); END;
