[package]
name = "my-fin-tauri"
version = "0.1.0"
description = "My Fin desktop and mobile application"
authors = ["Lucas Suares"]
edition = "2021"

[lib]
name = "my_fin_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "my-fin"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.37", features = ["bundled"] }
